//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlazorMenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlazorMenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorMenu.Resources.BlazorMenuResources", typeof(BlazorMenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        internal static string _1d {
            get {
                return ResourceManager.GetString("_1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the address is correct and that the page hasn&apos;t moved..
        /// </summary>
        internal static string _404Message {
            get {
                return ResourceManager.GetString("_404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try refreshing the page, or going back and attempting the action again..
        /// </summary>
        internal static string _500Message {
            get {
                return ResourceManager.GetString("_500Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string _AllRightsReserved {
            get {
                return ResourceManager.GetString("_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string _Author {
            get {
                return ResourceManager.GetString("_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string _ChangePassword {
            get {
                return ResourceManager.GetString("_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        internal static string _CompanyID {
            get {
                return ResourceManager.GetString("_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string _ContactUs {
            get {
                return ResourceManager.GetString("_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture ID.
        /// </summary>
        internal static string _CultureID {
            get {
                return ResourceManager.GetString("_CultureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string _Database {
            get {
                return ResourceManager.GetString("_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server.
        /// </summary>
        internal static string _DatabaseServer {
            get {
                return ResourceManager.GetString("_DatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        internal static string _Earlier {
            get {
                return ResourceManager.GetString("_Earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photo.
        /// </summary>
        internal static string _EditPhoto {
            get {
                return ResourceManager.GetString("_EditPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrontEnd Version.
        /// </summary>
        internal static string _FrontEndVersion {
            get {
                return ResourceManager.GetString("_FrontEndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string _HoursAgo {
            get {
                return ResourceManager.GetString("_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Now.
        /// </summary>
        internal static string _JustNow {
            get {
                return ResourceManager.GetString("_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Password Update.
        /// </summary>
        internal static string _LastUpdatePassword {
            get {
                return ResourceManager.GetString("_LastUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _Login {
            get {
                return ResourceManager.GetString("_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string _Logout {
            get {
                return ResourceManager.GetString("_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        internal static string _MarkAllAsRead {
            get {
                return ResourceManager.GetString("_MarkAllAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Version.
        /// </summary>
        internal static string _MenuVersion {
            get {
                return ResourceManager.GetString("_MenuVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _Message {
            get {
                return ResourceManager.GetString("_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Date.
        /// </summary>
        internal static string _MessageDate {
            get {
                return ResourceManager.GetString("_MessageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string _MinutesAgo {
            get {
                return ResourceManager.GetString("_MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string _MoreInformation {
            get {
                return ResourceManager.GetString("_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications found. You are up to date!.
        /// </summary>
        internal static string _NoNotification {
            get {
                return ResourceManager.GetString("_NoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string _Notifications {
            get {
                return ResourceManager.GetString("_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you&apos;re looking for is not found..
        /// </summary>
        internal static string _PageNotFound {
            get {
                return ResourceManager.GetString("_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _Password {
            get {
                return ResourceManager.GetString("_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string _Profile {
            get {
                return ResourceManager.GetString("_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &amp; Account.
        /// </summary>
        internal static string _ProfileAccount {
            get {
                return ResourceManager.GetString("_ProfileAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string _Read {
            get {
                return ResourceManager.GetString("_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        internal static string _Unread {
            get {
                return ResourceManager.GetString("_Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string _Update {
            get {
                return ResourceManager.GetString("_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string _UserID {
            get {
                return ResourceManager.GetString("_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string _Username {
            get {
                return ResourceManager.GetString("_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string _ViewAll {
            get {
                return ResourceManager.GetString("_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops, something went wrong!.
        /// </summary>
        internal static string _Whoops {
            get {
                return ResourceManager.GetString("_Whoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to log you in..
        /// </summary>
        internal static string Auth_E001 {
            get {
                return ResourceManager.GetString("Auth_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        internal static string Auth_E002 {
            get {
                return ResourceManager.GetString("Auth_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user credentials..
        /// </summary>
        internal static string Auth_E003 {
            get {
                return ResourceManager.GetString("Auth_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect captcha..
        /// </summary>
        internal static string Auth_E004 {
            get {
                return ResourceManager.GetString("Auth_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string Auth_E005 {
            get {
                return ResourceManager.GetString("Auth_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        internal static string ChangePassword_M001 {
            get {
                return ResourceManager.GetString("ChangePassword_M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string ChangePassword_P001 {
            get {
                return ResourceManager.GetString("ChangePassword_P001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ChangePassword_P002 {
            get {
                return ResourceManager.GetString("ChangePassword_P002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ChangePassword_P003 {
            get {
                return ResourceManager.GetString("ChangePassword_P003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old Password field is required..
        /// </summary>
        internal static string ChangePassword_V001 {
            get {
                return ResourceManager.GetString("ChangePassword_V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Password field is required..
        /// </summary>
        internal static string ChangePassword_V002 {
            get {
                return ResourceManager.GetString("ChangePassword_V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Confirmation Password field is required..
        /// </summary>
        internal static string ChangePassword_V003 {
            get {
                return ResourceManager.GetString("ChangePassword_V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string ChangePassword_V004 {
            get {
                return ResourceManager.GetString("ChangePassword_V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        internal static string ChangePassword_V005 {
            get {
                return ResourceManager.GetString("ChangePassword_V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your password only after {0} days from your last update..
        /// </summary>
        internal static string ChangePassword_V006 {
            get {
                return ResourceManager.GetString("ChangePassword_V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use your last {0} passwords..
        /// </summary>
        internal static string ChangePassword_V007 {
            get {
                return ResourceManager.GetString("ChangePassword_V007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one letter..
        /// </summary>
        internal static string ChangePassword_V008 {
            get {
                return ResourceManager.GetString("ChangePassword_V008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        internal static string ChangePassword_V009 {
            get {
                return ResourceManager.GetString("ChangePassword_V009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        internal static string ChangePassword_V010 {
            get {
                return ResourceManager.GetString("ChangePassword_V010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        internal static string ChangePassword_V011 {
            get {
                return ResourceManager.GetString("ChangePassword_V011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        internal static string ChangePassword_V012 {
            get {
                return ResourceManager.GetString("ChangePassword_V012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain the user ID..
        /// </summary>
        internal static string ChangePassword_V013 {
            get {
                return ResourceManager.GetString("ChangePassword_V013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to {0} is null..
        /// </summary>
        internal static string Common_E001 {
            get {
                return ResourceManager.GetString("Common_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string Common_E002 {
            get {
                return ResourceManager.GetString("Common_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string Common_E003 {
            get {
                return ResourceManager.GetString("Common_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realta Chakradarma.
        /// </summary>
        internal static string CONST_CompanyName {
            get {
                return ResourceManager.GetString("CONST_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2025.
        /// </summary>
        internal static string CONST_CopyrightYear {
            get {
                return ResourceManager.GetString("CONST_CopyrightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        internal static string MenuTab_E001 {
            get {
                return ResourceManager.GetString("MenuTab_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetPageType must inherit from R_Page..
        /// </summary>
        internal static string Page_E001 {
            get {
                return ResourceManager.GetString("Page_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info updated successfully..
        /// </summary>
        internal static string Profile_M001 {
            get {
                return ResourceManager.GetString("Profile_M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required..
        /// </summary>
        internal static string Profile_V001 {
            get {
                return ResourceManager.GetString("Profile_V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address field is required..
        /// </summary>
        internal static string Profile_V002 {
            get {
                return ResourceManager.GetString("Profile_V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred for message ID {0} : {1}..
        /// </summary>
        internal static string Resource_E001 {
            get {
                return ResourceManager.GetString("Resource_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditContext is required but was not provided..
        /// </summary>
        internal static string ValidationMessage_E001 {
            get {
                return ResourceManager.GetString("ValidationMessage_E001", resourceCulture);
            }
        }
    }
}
